defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

title: Chris Haslehurst
description: Thoughts on programming, games, and programming games.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minima
google_analytics: UA-165907236-1
