author:
  name: John Smith
  email: "john.smith@foobar.com"

title: Chris Haslehurst
description: Thoughts on programming, games, and programming games.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-165907236-1

theme: minima
show_excerpts: true

minima:
  social_links:
    twitter: chrishaslehurst
    github: chrishaslehurst
    linkedin: chrishaslehurst

disqus:
shortname: chrishaslehurst
