defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

author:
  name: Chris Haslehurst
  email: "chrishaslehurst@gmail.com"

title: Chris Haslehurst
description: Thoughts on programming, games, and programming games.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-165907236-1

theme: minima
show_excerpts: true

minima:
  skin: solarized-dark 
  social_links:
    twitter: chrishaslehurst
    github: chrishaslehurst
    linkedin: chrishaslehurst

disqus:
shortname: chrishaslehurst
